version: '3.4'

services:
  society-message-queue:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  society-api-gateway:
    image: society-api-gateway
    ports:
      - "5000:80"
    links:
      - citizen-service
      - universe-service

  citizen-service:
    image: society-service-citizen
    environment:
      - ConnectionStrings__CitizenDb=Server=192.168.1.6,1433;Database=CitizenDb.Dev;User Id=develop;Password=develop;MultipleActiveResultSets=True;
      - MassTransit__Username=guest
      - MassTransit__Password=guest
      - MassTransit__Host=society-message-queue
      - QueueEndpoints__Universe=citizen-universe-dev
      - QueueEndpoints__Citizen=citizen-dev
    depends_on:
      - society-message-queue
      
  universe-service:
    image: society-service-universe
    environment:
      - ConnectionStrings__UniverseDb=Server=192.168.1.6,1433;Database=UniverseDb.Dev;User Id=develop;Password=develop;MultipleActiveResultSets=True;
      - MassTransit__Username=guest
      - MassTransit__Password=guest
      - MassTransit__Host=society-message-queue
      - QueueEndpoints__Universe=universe-dev
      - QueueEndpoints__Citizen=universe-citizen-dev
      - TickLength=10
    depends_on:
      - society-message-queue