version: '3.4'

services:
  society-message-queue:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  society-api-gateway:
    image: society-api-gateway
    ports:
      - "5000:80"
    links:
      - citizen-service
      - universe-service

  citizen-service:
    image: society-service-citizen
    environment:
      - ConnectionStrings__CitizenDb=Server=192.168.1.6,1433;Database=CitizenDb.Dev;User Id=develop;Password=develop;MultipleActiveResultSets=True;
      - MassTransit__Username=guest
      - MassTransit__Password=guest
      - MassTransit__Host=society-message-queue
      - Consul__Discovery=http://consul:8500
      - Consul__Host=citizen-service
      - Consul__Port=80
      - Consul__Name=citizen-service
      
  universe-service:
    image: society-service-universe
    environment:
      - ConnectionStrings__UniverseDb=Server=192.168.1.6,1433;Database=UniverseDb.Dev;User Id=develop;Password=develop;MultipleActiveResultSets=True;
      - MassTransit__Username=guest
      - MassTransit__Password=guest
      - MassTransit__Host=society-message-queue
      - TickLength=10
      - Consul__Discovery=http://consul:8500
      - Consul__Host=universe-service
      - Consul__Port=80
      - Consul__Name=universe-service
      - society-message-queue
    
  consul:
    ports:
      - "5800:5800"
      - "8600:8600/udp"
    image: consul:latest
    command: "agent -server -bootstrap -ui -client=0.0.0.0"